spring:
  datasource:
    url: jdbc:mysql://localhost:8082/shoppingmall
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql:true

logging:
  level:
    org.hibernate.sql: debug

JWT_SECRET_KEY: ${JWT_SECRET_KEY}